[package]
name = "actix-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-cors = "0.6.1"
actix-web = "4.1.0"
types = { path= "../types"}
serde = "1.0.140"
reqwest = { version = "0.11.11", features = ["json"]}
env_logger = "0.9.0"
log = "0.4.0"
r2d2 = "0.8.10"
r2d2_postgres = "0.18.1"
oauth2 = { version = "4" }
jsonwebtoken= "8.1.1"
base64 = "0.13.0"
serde_json = "1.0.82"
anyhow = "1.0.60"